name: Run Linux Commands in Docker

on: [push]

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string

jobs:
  run-in-docker:
    # Use a standard Linux runner provided by GitHub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run commands in a specific Docker container
      # This action uses a specific Docker image
      uses: docker://ubuntu:latest
      with:
        # Commands to run in the container
        args: /bin/bash

