name: Interactive Ubuntu Docker
on: [workflow_dispatch] # Allows you to start it manually

jobs:
  interactive-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Start Docker Container
        run: |
          # Run Ubuntu in background with sleep to keep it alive
          docker run -d --name my-ubuntu ubuntu sleep infinity

      - name: Setup Tmate Session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
